name: manage-azure-policy-04f420ce
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Blob_Private_Endpoint_Deploy-DNSZoneGroup-For-Blob-PrivateEndpoint/**'
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-File_Private_Endpoint_Deploy-DNSZoneGroup-For-File-PrivateEndpoint/**'
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Key_Vault_Private_Endpoint_Deploy-DNSZoneGroup-For-KeyVault-PrivateEndpoint/**'
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Queue_Private_Endpoint_Deploy-DNSZoneGroup-For-Queue-PrivateEndpoint/**'
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_SQL_Private_Endpoint_Deploy-DNSZoneGroup-For-Sql-PrivateEndpoint/**'
#      - 'ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Table_Private_Endpoint_Deploy-DNSZoneGroup-For-Table-PrivateEndpoint/**'
#      - .github/workflows/manage-azure-policy-04f420ce.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_04f420ce}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Blob_Private_Endpoint_Deploy-DNSZoneGroup-For-Blob-PrivateEndpoint/**
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-File_Private_Endpoint_Deploy-DNSZoneGroup-For-File-PrivateEndpoint/**
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Key_Vault_Private_Endpoint_Deploy-DNSZoneGroup-For-KeyVault-PrivateEndpoint/**
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Queue_Private_Endpoint_Deploy-DNSZoneGroup-For-Queue-PrivateEndpoint/**
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_SQL_Private_Endpoint_Deploy-DNSZoneGroup-For-Sql-PrivateEndpoint/**
          ESLZ-Export/policies/Deploy_DNS_Zone_Group_for_Storage-Table_Private_Endpoint_Deploy-DNSZoneGroup-For-Table-PrivateEndpoint/**
